version: '2'
services:
  jekyll:
    # image: jekyll/jekyll:pages
    image: jekyll/jekyll:stable
    command: jekyll serve --watch --incremental
    ports:
    - "4000:4000"
    volumes:
    - .:/srv/jekyll
